<%-- 
    Document   : verParcelas
    Created on : 01-jun-2021, 23:42:03
    Author     : Lidia Baixauli de la Villa
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h2>Parcelas del huerto</h2>
        <!-- Image Map Generated by http://www.image-map.net/ -->
         <map name="image-map">
            <area id="p1" target="_blank" alt="Parcela A01" title="Parcela A01" href="#" coords="61,334,157,279,217,403,133,465" shape="poly">
            <area target="" alt="A02" title="A02" href="#" coords="133,465,216,402,283,534,192,585" shape="poly">
        </map>
       
        <img src="../resources/imagenes/parcelas.jpg" usemap="#image-map">
        <!--panel informacion-->
    </body>
</html>
